# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P3u6iA4zRkvOFDGfSA9v2b6eir3JWOuV
"""

import random
import numpy as np
import matplotlib.pyplot as plt

def rand_samples(m, b, n_points, rand_param):
    pos_p = n_points // 2
    neg_p = n_points - pos_p
    X = []
    Y = []
    for i in range(pos_p):
        x = random.randint(0,rand_param)
        y = m * x + b - random.randint(5,rand_param)
        X.append([x,y,1])
        Y.append([1])

    for i in range(neg_p):
        x = random.randint(0,rand_param)
        y = m * x + b + random.randint(5,rand_param)
        X.append([x,y,1])
        Y.append([-1])

    X = np.array(X)
    Y = np.array(Y)
    return X, Y

def sign(x, w):
    return 1 if np.dot(x, w)>=0 else -1

def PLA(X, Y, w):
    num = len(X)
    w_change = 0
    for iter in range(100):
        flag = 0
        for i in range(num):
            if sign(X[i],w)!=Y[i]:
                w = w + Y[i]*np.reshape(X[i], (len(X[i]),1))
                w_change += 1
                flag = 1
        if flag == 0:
            break
    return w, w_change

def Pocket(X, Y, w):
    num = len(X)
    w_change = 0
    error = len(X)
    tmp_w = w
    for iter in range(100):
        tmp_error = 0
        for i in range(num):
            if sign(X[i],w)!=Y[i]:
                w = w + Y[i]*np.reshape(X[i], (len(X[i]),1))
                break;
        for j in range(num):
            if sign(X[j],w)!=Y[j]:
                tmp_error += 1
        if tmp_error < error:
           error = tmp_error
           w_change += 1
    
    return w, w_change

if __name__ == '__main__':
    # y = mx + b
    m, b = 2, 1

    # other parameters
    n_points = 30
    rand_param = 30
    pos_num = int(n_points / 2)

    # plot function curve
    x = np.arange(rand_param + 1)   # x = [0, 1,..., rand_param]
    y = m * x + b
    plt.figure(figsize=(8,8))
    plt.subplot(321)
    plt.plot(x, y)

    # randomly generate points
    X,Y = rand_samples(m, b, n_points, rand_param)

    # plot random points. Blue: positive, red: negative
    plt.plot(X[:pos_num,0], X[:pos_num,1], 'o', color='blue')   # positive
    plt.plot(X[pos_num:,0], X[pos_num:,1], 'o', color='red')    # negative

    # PLA
    w0 = np.zeros((3,1))
    w,iter1 = PLA(X, Y, w0)

    x2 = np.arange(rand_param + 1)
    y2 = (-w[0] * x2 - w[2])/w[1]
    plt.subplot(322)
    plt.plot(x2, y2)
    plt.plot(X[:pos_num,0], X[:pos_num,1], 'o', color='blue')   # positive
    plt.plot(X[pos_num:,0], X[pos_num:,1], 'o', color='red')    # negative
    print(f"PLA-1 iterations = {iter1}")

    # 2
    plt.subplot(323)
    plt.plot(x, y)
    X,Y = rand_samples(m, b, n_points, rand_param)
    plt.plot(X[:pos_num,0], X[:pos_num,1], 'o', color='blue')   # positive
    plt.plot(X[pos_num:,0], X[pos_num:,1], 'o', color='red')    # negative

	# PLA
    w,iter2 = PLA(X, Y, w0)
    x2 = np.arange(rand_param + 1)
    y2 = (-w[0] * x2 - w[2])/w[1]
    plt.subplot(324)
    plt.plot(x2, y2)
    plt.plot(X[:pos_num,0], X[:pos_num,1], 'o', color='blue')   # positive
    plt.plot(X[pos_num:,0], X[pos_num:,1], 'o', color='red')    # negative
    print(f"PLA-2 iterations = {iter2}")

	# 3
    plt.subplot(325)
    plt.plot(x, y)
    X,Y = rand_samples(m, b, n_points, rand_param)
    plt.plot(X[:pos_num,0], X[:pos_num,1], 'o', color='blue')   # positive
    plt.plot(X[pos_num:,0], X[pos_num:,1], 'o', color='red')    # negative

	# PLA
    w,iter3 = PLA(X, Y, w0)
    x2 = np.arange(rand_param + 1)
    y2 = (-w[0] * x2 - w[2])/w[1]
    plt.subplot(326)
    plt.plot(x2, y2)
    plt.plot(X[:pos_num,0], X[:pos_num,1], 'o', color='blue')   # positive
    plt.plot(X[pos_num:,0], X[pos_num:,1], 'o', color='red')    # negative
    print(f"PLA-3 iterations = {iter3}")
    
    plt.show
    print("FOR PLA-------")
    print(f"Average Iterations ={(iter1+iter2+iter3)/3}")