# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15gQEW-YIo66OgRVerfDIWeNixUD6DePJ
"""

import numpy as np
import matplotlib.pyplot as plt
import random


def rand_samples(m, b, n_points, rand_param):
    pos_p = n_points // 2
    neg_p = n_points - pos_p
    X = []
    Y = []
    for i in range(pos_p):
        x = random.randint(0,rand_param)
        y = m * x + b - random.randint(5,rand_param)
        X.append([x,y,1])
        Y.append([1])

    for i in range(neg_p):
        x = random.randint(0,rand_param)
        y = m * x + b + random.randint(5,rand_param)
        X.append([x,y,1])
        Y.append([-1])

    X = np.array(X)
    Y = np.array(Y)
    return X, Y

if __name__ == '__main__':
    # y = mx + b
    m, b = 2, 1

    # other parameters
    n_points = 30
    rand_param = 30
    pos_num = int(n_points / 2)

    # plot function curve
    x = np.arange(rand_param + 1)   # x = [0, 1,..., rand_param]
    y = m * x + b
    plt.plot(x, y)

    # randomly generate points
    X,Y = rand_samples(m, b, n_points, rand_param)

    # plot random points. Blue: positive, red: negative
    plt.plot(X[:pos_num,0], X[:pos_num,1], 'o', color='blue')   # positive
    plt.plot(X[pos_num:,0], X[pos_num:,1], 'o', color='red')    # negative
    plt.show()